on:
  pull_request:
  push:
    paths:
      - 'packages/**/*.ts'
      - 'packages/**/*.prisma'
      - 'packages/**/package.json'
      - 'packages/**/tsconfig.json'
      - 'tsconfig.json'
      - 'package.json'

jobs:
  eslint:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Install Node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: Install dependencies
      run: yarn --immutable

    - name: Run ESLint
      run: npx eslint packages

  typescript:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    name: TypeScript Transpile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: Install dependencies
      run: yarn --immutable

    - name: Generate Prisma schema
      run: yarn prisma

    - name: TypeScript Test
      run: yarn typecheck
