on: [push, pull_request]

jobs:
  eslint:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Turbo cache
      id: turbo-cache
      uses: actions/cache@v3
      with:
        path: .turbo
        key: turbo-${{ github.job }}-${{ github.ref_name }}-${{ github.sha }}
        restore-keys: |
          turbo-${{ github.job }}-${{ github.ref_name }}-

    - name: Install Node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: yarn.lock
    - name: Install dependencies
      run: yarn --immutable
    - name: Run ESLint
      run: yarn format --cache-dir=".turbo"
  typescript:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    name: TypeScript Transpile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
        cache-dependency-path: yarn.lock
    - name: Install dependencies
      run: yarn --immutable
    - name: Generate Prisma schema
      run: yarn prisma --cache-dir=".turbo"
    - name: TypeScript Test
      run: yarn typecheck --cache-dir=".turbo"
