on: [push, pull_request]

jobs:
  eslint:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --immutable
    - name: Run ESLint
      uses: icrawl/action-eslint@v1
      with:
        custom-glob: packages
  typescript:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    name: TypeScript Transpile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --immutable
    - name: Generate Prisma schema
      run: npx turbo run generate:postgres
    - name: TypeScript Test
      run: npx turbo run check
