on: [push, pull_request]

jobs:
  tsc:
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository
    name: TypeScript Transpile
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node v18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install
    - name: Generate Prisma schema
      run: npx turbo run generate:postgres
    - name: tsc
      uses: icrawl/action-tsc@v1
